spring:
  datasource:
    url: jdbc:mysql://10.222.29.148:3306/parkingsmart?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  activemq:
    broker-url: tcp://10.222.29.148:61616
    user: ita01-team01
    in-memory: false
    password: strongpassword
    pool:
      enabled: false
      max-connections: 50
      expiry-timeout: 10000
      idle-timeout: 30000
    packages:
      trust-all: true
server:
  port: 8090


